### ISSUE TITLE
Possible alternative/new API

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-icap#1]
I wasn't sure when creating the API what would the best approach and went with the simplest one.

Here is a different, object based approach:

``` js
ICAP.fromAddress(<address>) (returns <this> for chaining) - creates an instance based on the address
ICAP.fromAsset(<asset obj>) (returns <this> for chaining) - creates an instance based on the asset
ICAP.parse(<icap>) (returns <this> for chaining) - creates an instance based on the ICAP
ICAP.toBBAN() - return encoded BBAN
ICAP.toAddress() - return address
ICAP.toAsset() - return asset
ICAP.toString([bool: pretty printed]) - returns the encoded IBAN/ICAP
```

Alternative names for `parse`:
- `parseICAP`
- `parseIBAN`
- `fromICAP`
- `fromIBAN`

Any suggestions?

**Comment by frozeman** [comment]
Im not 100% sure about the naming conventions, but i wouldn't return the instance, and rather keep it as a simple conversion library.
